# Generated by Django 4.0.3 on 2022-03-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_App', '0007_remove_review_id_alter_review_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='review_text',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
