# Generated by Django 4.0.3 on 2022-03-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_App', '0008_order_review_score_order_review_text_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Order Pending', 'Pending'), ('Order Accepted', 'Preparing Item'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancel Order', 'Cancelled')], default=('Order Pending', 'Pending'), max_length=200),
        ),
    ]
