# Generated by Django 4.0.3 on 2022-03-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_App', '0010_order_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Order Pending'), ('ACCEPTED', 'Preparing Item'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default=('PENDING', 'Order Pending'), max_length=200),
        ),
    ]
