# Generated by Django 4.0.3 on 2022-03-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_App', '0011_alter_order_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='active_status',
        ),
    ]
