# Generated by Django 4.0.3 on 2022-03-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders_App', '0014_order_cost_alter_item_id_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
